# Generated by Django 5.0.4 on 2024-05-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.ImageField(default=1234, upload_to=''),
            preserve_default=False,
        ),
    ]
