# Generated by Django 5.0.4 on 2024-05-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_alter_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.ImageField(default=1234, upload_to=''),
            preserve_default=False,
        ),
    ]
